---
service: serverless-nodejs

frameworkVersion: '^2.0.0'

variablesResolutionMode: 20210219

plugins:
  - serverless-domain-manager
  - serverless-jetpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: ${env:AWS_DEFAULT_REGION, 'us-east-1'}
  stage: stg
  logRetentionInDays: 30
  apiGateway:
    shouldStartNameWithService: true
  lambdaHashingVersion: 20201221
  environment:
    NODE_ENV: production

custom:
  domain: makenew.razorx.app
  customDomain:
    domainName: ${self:provider.stage}.${self:service}.${self:custom.domain}
    endpointType: regional
    createRoute53Record: true

package:
  individually: true
  exclude:
    - '*/**.spec.js'
    - .editorconfig
    - .eslintrc.json
    - .eslintrc.json
    - .github/**
    - .nvmrc
    - .nyc_output/**
    - .nycrc.json
    - .prettierrc.json
    - CHANGELOG.md
    - README.md
    - ava.config.js
    - coverage/**
    - examples/**
    - makenew.sh
    - test/**
    - yarn.lock

functions:
  todo:
    handler: handlers/todo.default
    events:
      - http:
          method: get
          path: /todo
