---
service: serverless-nodejs

frameworkVersion: "^1.58.0"

plugins:
  - serverless-domain-manager
  - serverless-offline
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  region: ${env:AWS_DEFAULT_REGION, 'us-east-1'}
  stage: ${opt:stage, env:SERVERLESS_STAGE, 'dev'}
  logRetentionInDays: 30
  environment:
    NODE_ENV: production

custom:
  domain: makenew.razorx.app
  customDomain:
    domainName: ${self:provider.stage}.${self:service}.${self:custom.domain}
    endpointType: regional
    createRoute53Record: true
  webpack:
    packager: yarn
    includeModules:
      forceExclude:
        - aws-sdk

package:
  individually: true

functions:
  todo:
    handler: handlers/todo.default
    events:
      - http:
          method: get
          path: /todo
