---
service: serverless-nodejs

frameworkVersion: '^2.66.2'

variablesResolutionMode: 20210326
configValidationMode: error

provider:
  name: aws
  architecture: arm64
  runtime: nodejs14.x
  region: ${env:AWS_DEFAULT_REGION, 'us-east-1'}
  stage: stg
  logRetentionInDays: 30
  httpApi:
    payload: '2.0'
    disableDefaultEndpoint: true
  apiGateway:
    shouldStartNameWithService: true
  eventBridge:
    useCloudFormation: true
  deploymentBucket:
    blockPublicAccess: true
  lambdaHashingVersion: 20201221
  environment:
    NODE_ENV: production

package:
  individually: true
  patterns:
    - '!*/**.spec.js'
    - '!.c8rc.json'
    - '!.editorconfig'
    - '!.eslintrc.json'
    - '!.github/**'
    - '!.gitignore'
    - '!.nvmrc'
    - '!.prettierrc.json'
    - '!CHANGELOG.md'
    - '!README.md'
    - '!ava.config.js'
    - '!coverage/**'
    - '!examples/**'
    - '!fixtures/**'
    - '!makenew.sh'
    - '!serverless.yml'
    - '!test/**'
    - '!package-lock.json'

functions:
  todo:
    handler: handlers/todo.handler
